/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

public class App {

    public static void main(String[] args) {
        System.out.println("Please enter the game number and press Enter.");
        System.out.println("1 - Greet");
        System.out.println("2 - Even");
        System.out.println("3 - Calc");
        System.out.println("4 - GCD");
        System.out.println("0 - Exit");
        int chois = Engine.numbersScanner();
        if (chois == 1) {
            Engine.getYourChoic(chois);
            String run = Cli.greeting();
        } else if (chois == 2) {
            Engine.getYourChoic(chois);
            EvenOrOdd.evenOrOdd();
        } else if (chois == 3) {
            Engine.getYourChoic(chois);
            Calc.calc();
        } else if (chois == 4) {
            Engine.getYourChoic(chois);
            Gcd.gcd();
        }
    }
}
