/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import hexlet.code.games.Calc;
import hexlet.code.games.EvenOrOdd;
import hexlet.code.games.Gcd;
import hexlet.code.games.Progression;

public class App {

    public static void main(String[] args) {
        System.out.println("Please enter the game number and press Enter.");
        System.out.println("1 - Greet");
        System.out.println("2 - Even");
        System.out.println("3 - Calc");
        System.out.println("4 - GCD");
        System.out.println("5 - Progression");
        System.out.println("0 - Exit");
        int choice = Engine.numbersScanner();
        if (choice == 1) {
            Engine.getYourChoic(choice);
            String run = Cli.greeting();
        } else if (choice == 2) {
            Engine.getYourChoic(choice);
            EvenOrOdd.evenOrOdd();
        } else if (choice == 3) {
            Engine.getYourChoic(choice);
            Calc.calc();
        } else if (choice == 4) {
            Engine.getYourChoic(choice);
            Gcd.gcd();
        } else if (choice == 5) {
            Engine.getYourChoic(choice);
            Progression.progression();
        }
    }
}
