/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import hexlet.code.games.Calc;
import hexlet.code.games.EvenOrOdd;
import hexlet.code.games.Progression;
import hexlet.code.games.Prime;
import hexlet.code.games.Gcd;

import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);

        System.out.println("Please enter the game number and press Enter.");
        System.out.println("1 - Greet");
        System.out.println("2 - Even");
        System.out.println("3 - Calc");
        System.out.println("4 - GCD");
        System.out.println("5 - Progression");
        System.out.println("6 - Prime");
        System.out.println("0 - Exit");
        String selectedGame = scanner.nextLine();
        System.out.println("Your choice: " + selectedGame + "\n");
        switch (selectedGame) {
            case "1":
                Cli.greeting();
                break;
            case "2":
                EvenOrOdd.evenOrOdd();
                break;
            case "3":
                Calc.calc();
                break;
            case "4":
                Gcd.gcd();
                break;
            case "5":
                Progression.progression();
                break;
            case "6":
                Prime.prime();
                break;
            case "0":
                System.out.println("Good bay!");
                break;
            default:
                System.out.println("Unknown game select!" + selectedGame);
                break;
        }
    }
}
